version: "1.0"
name: vue2-cos-deploy
displayName: Vue2 Build And Deploy To COS
triggers:
  push:
    branches:
      precise:
        - master
        - main

stages:
  - name: build_and_deploy
    displayName: 构建并上传 COS
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_vue2_and_upload_cos
        displayName: 构建 Vue2 并上传 COS
        nodeVersion: 14.16.0
        commands:
          - npm ci
          - npm run build
          - python3 -m pip install coscmd
          - coscmd config -a ${COS_SECRET_ID} -s ${COS_SECRET_KEY} -b ${COS_BUCKET_NAME} -r ${COS_BUCKET_REGION}
          - coscmd upload -r ./dist/ /dist/
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist

      - step: publish@general_artifacts
        name: publish_dist_artifact
        displayName: 上传构建产物
        dependArtifact: BUILD_ARTIFACT
        artifactRepository: default
        artifactName: vue2-dist
